[profile.default]
  src = "src"
  libs = ["lib"]
  out = "out"
  test = "test"
  script = "script"
  fuzz = { runs = 1_000 }
  evm_version = "paris"
  via_ir = false
  # Sphinx settings:
  build_info = true
  extra_output = ['storageLayout']
  fs_permissions = [{ access = "read", path = "./out"}, { access = "read-write", path = "./cache"}]
  always_use_create_2_factory = true



[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 300
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  polygon_mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
